# For help see https://www.jenkins.io/redirect/continuous-delivery-of-plugins

name: 'Jenkins CD'
on:
  workflow_dispatch:
  check_run:
    types:
      - completed

jobs:
  maven-cd:
    uses: jenkins-infra/github-reusable-workflows/.github/workflows/maven-cd.yml@v1
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
