name: 'Release Drafter'

on:
  push:
    branches:
      - master
      - main

jobs:
  update-release-draft:
    name: 'Update Release Draft'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
