name: 'UI Tests'

on:
  push:
    branches:
      - main
  pull_request_target:

jobs:
  ui-tests:
    strategy:
      fail-fast: false
      matrix:
        browser: [ firefox-container, chrome-container ]

    runs-on: [ubuntu-latest]
    name: ${{ matrix.browser }}

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9
      - name: Build got-forensics plugin and download dependencies
        run: mvn -V --color always -ntp verify -Pskip --file plugin/pom.xml
      - name: Run UI tests on ${{ matrix.browser }}
        env:
          BROWSER: ${{ matrix.browser }}
          SKIP_UPDATES: 'true'
        run: mvn -V --color always -ntp test --file ui-tests/pom.xml -Dquite -Dgpg.skip -Dsurefire.rerunFailingTestsCount=1
